[package]
name = "dada-parser"
version.workspace = true
edition.workspace = true

[dependencies]
dada-ir-ast = { version = "0.1.0", path = "../dada-ir-ast" }
dada-util = { version = "0.1.0", path = "../dada-util" }
salsa = { workspace = true }
