[package]
name = "dada-lsp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dada-lang = { version = "0.1.0", path = "../dada-lang" }
dada-util = { version = "0.1.0", path = "../dada-util" }
lsp-server = "0.7.7"
