[workspace]
members = [".", "components/*"]

# Exclude xtask so it isn't installed with `cargo install`
default-members = [
  ".",
  "components/dada-*",
]

[package]
name = "dada"
version = "0.1.0"
edition = "2021"
default-run = "dada"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[[test]]
#name = "harness"
#harness = false

[dependencies]
anyhow = "1.0.86"
dada-lang = { path = "components/dada-lang" }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
