[package]
name = "dada-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dada-util-procmacro = { version = "0.1.0", path = "../dada-util-procmacro" }
fxhash = "0.2.1"
imstr = "0.2.0"
indexmap = "2.6.0"
salsa = { workspace = true }
