[package]
name = "dada-util-procmacro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
synstructure = "0.13.1"

[lib]
proc-macro = true
