[package]
name = "dada-util-procmacro"
version.workspace = true
edition.workspace = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit", "visit-mut"] }
synstructure = "0.13.1"

[lib]
proc-macro = true
