[package]
name = "dada-ir-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
annotate-snippets = "0.11.4"
dada-util = { version = "0.1.0", path = "../dada-util" }
salsa = { git = "https://github.com/salsa-rs/salsa.git" }
url = "2.5.3"
