[package]
name = "dada-ir-ast"
version = "0.1.0"
edition = "2021"

[dependencies]
annotate-snippets = { workspace = true }
dada-util = { version = "0.1.0", path = "../dada-util" }
salsa = { workspace = true }
url = { workspace = true }
