[package]
name = "dada-3p"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
structopt = "0.3.26"
salsa = { git = "https://github.com/salsa-rs/salsa.git" }
tokio = { version = "1.38.0", features = ["full"] }
imstr = "0.2.0"
fxhash = "0.2.1"
indexmap = "2.2.6"
